### ISSUE TITLE
NDTiffStorage in pycro-manager

### ISSUE THREAD

**Issue by ischoegl** [micro-manager/NDTiffStorage#10]
@henrypinkard ... `Acquisition`events in `pycro-manager` create TIFF files, which, however, appear to be flat (i.e. they aren't ND Hyperstacks). Is there a way to preserve `axes` defined in events?

Further, none of the metadata shown in the micro-magellan window appears to be saved to TIFF. 

**PS:** The code I'm using is
```python
import pycromanager as pm

if __name__ == '__main__':

    exposures = [.01, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]
    with pm.Acquisition(directory='.', name='darkframes') as acq:
        events = []
        for rep in range(50):
            for idx, exposure in enumerate(exposures):
                evt = {'axes': {'time': 0, 'repetition': rep, 'exposure': idx}, 'exposure': exposure}
                events.append(evt)

        acq.acquire(events)
```

**Comment by henrypinkard** [comment]
Where are you trying to open these data? And what exactly do you mean by ND hyperstacks. Are you following the pycro-manager data opening tutorial instructions?

**Comment by ischoegl** [comment]
I am currently checking with ImageJ itself (e.g. fiji), but will eventually load using [tifffile](https://github.com/cgohlke/tifffile), both of which are able to load n-dimensional TIFF stacks.

**Comment by henrypinkard** [comment]
It is, but it is more flexible than that model, since that model requires every image be present along every axis. For this reason the hack glue code that allows hyperstack opening in ImageJ is removed, though it probably wouldn't work for your case since you don't have to TCZ axes. If you're going to use a python tiff reader anyway, you might as well use the one provided by pycro-manager, since it will be higher performance

**Comment by ischoegl** [comment]
Thanks for the comments. Unfortunately our image processing code base takes advantage of the regular N-dimensional structure of Hyperstacks or their `numpy` equivalent (we’re slicing across `numpy` dimensions using `numba` accelerated code), so we’ll stick with a standard TIFF implementation. We should still be able to use hooks within pycro-manager to save our output.

**Comment by cgohlke** [comment]
Is the NDTiffStorage format documented somewhere or are reference files available? I guess the format is different from [Micro-Manager_File_Formats](https://micro-manager.org/wiki/Micro-Manager_File_Formats), otherwise tifffile would be able to read it.

**Comment by ischoegl** [comment]
@cgohlke ... thanks for chiming in. Tifffile should be able to read it - I’m more concerned about getting information about dimensions/slices (tifffile has worked beautifully for Hyperstacks in this regard); I clearly have incomplete information at the moment as I’ve mostly looked at ImageJ imports thus far.

**Comment by cgohlke** [comment]
Can you share a file? I can try to add metadata reader and "Series" handler for the NDTiffStorage format to tifffile.

**Comment by henrypinkard** [comment]
Just look at the [documentation for reading data](https://pycro-manager.readthedocs.io/en/latest/read_data.html#opening-data-as-dask-array). You can open it up as big sliceable arrays. It's just not restricted the channel/z/t model of ImageJ (i.e. you can have arbitrary axes).

@cgohlke haven't written a formal specification, but it is very similar to micro-manager with some extra features built it. If you would like to add it to your library, probably easiest to just depend on `pycromanager`, since the python reader is already built

**Comment by ischoegl** [comment]
@henrypinkard ... dask is interesting, and thankfully works with numba (see [docs](https://examples.dask.org/applications/stencils-with-numba.html)). We’ll have to adapt our code base, but it looks like it’s worthwhile.

Are there any docs about how to access metadata?

**Comment by henrypinkard** [comment]
Yes, on that same link it describes how to access metadata.

@ischoegl Several of the questions you've asked are already described in the documentation. It is general good practice in any open source community to first try to solve the problem yourself, before asking for help. Like many developers in the open source community, I am working on on this project in parallel to other things, and if everyone asked for personalized help, I would not have time to do it all. If there are areas where the documentation or the code are not ideally suited to your purposes, it is much better to propose solutions and make pull requests than to ask for things to be adapted to your specific use case. Good luck with your project!

**Comment by ischoegl** [comment]
@henrypinkard ... I understand - I wouldn't have asked here if you hadn't stated `Open an issue if you're interested to learn more` on the Readme (I am contributing to open source myself and am aware of the issues you mention). So please do not assume that I am someone who is asking others to solve my problems.

Your project is interesting, but it seems like these are very early days. With extremely sparse documentation and departures from other ImageJ norms it is difficult, and I have to make a judgement call about whether this is worth pursuing. `pycro-manager` would simplify things for us, but we have our own in-house code that is mostly working already.

**Comment by eirinnm** [comment]
I know this is an old topic, but I've come across the same issue: Fiji cannot open ndtiff.index files, so the dimension information is lost. At the moment I can only open the TIFFs as flat images. This makes NDTiff less desirable than OME-TIFF which is supported by bio-formats.

Is there an implementation of NDTiffStorage for Fiji, perhaps a plugin that needs to be installed to enable the metadata to be read?

**Comment by henrypinkard** [comment]
Someone would need to write the Java code linking the Java NDTiff reading code with the BioFormats API, and then pull request it to bioformats so it can be distributed with FIJI. In theory not a huge project. Happy to provide more info if you have interest in taking it on
