### ISSUE TITLE
Dataset.as_array() flips X and Y dimensions

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/NDTiffStorage#105]
`Dataset.read_image().shape` returns (Y, X) dimensions, while `Dataset.as_array().shape[-2:]` returns (X, Y) dimensions

**Comment by ieivanov** [comment]
Strangely, calling `np.asarray(Dataset.as_array()).shape[-2:]` return (Y,X). Is this is a difference in convention between dask and numpy? That would be surprising to me.

**Comment by henrypinkard** [comment]
Agree that would be weird.

The correct ordering is (Y, X), yeah?

**Comment by ieivanov** [comment]
That's right, the correct ordering is (Y, X). If I read a single image with `tifffile` it comes out in that shape

**Comment by henrypinkard** [comment]
Do you want to look into the cause or shall I?

**Comment by ieivanov** [comment]
I'm a bit tied up these days, go ahead if you have bandwidth
