### ISSUE TITLE
Bug report: path separator is appended twice to file path

### ISSUE THREAD

**Issue by pavanramkumar** [micro-manager/NDTiffStorage#122]
once just before calling `read_index`:
https://github.com/micro-manager/NDTiffStorage/blob/main/python/ndtiff/nd_tiff_current.py#L187

and once inside `read_index`:
https://github.com/micro-manager/NDTiffStorage/blob/main/python/ndtiff/nd_tiff_current.py#L556

please let me know if i'm missing something trivial

**Comment by henrypinkard** [comment]
Thanks for the fix!
