### ISSUE TITLE
How to remove data in a specific axes of a ndtiff file?

### ISSUE THREAD

**Issue by svikolev** [micro-manager/NDTiffStorage#135]
I am using pycromager to acquire many very large datasets. I have a lot of very large ndtiff Dataset files where I want to keep most of the data but I would like to remove an axis (ex: channel 1, or z:0 ) because it does not contain anything valuable. I like the file format of ndtiff so I would like to keep it rather then using another package like tifffile to write the desired arrays to other files. How can I write a new dataset file in python including only the axes I care about?

**Comment by henrypinkard** [comment]
So you want to rewrite a new NDTiff file after the fact, with some axes deleted, Is that right? The only current writer for NDTiff is written in Java, so you'd have call Java code via python to do this. 

You could do this through the pycromanager python-java bridge by calling [java code from python](https://pycro-manager.readthedocs.io/en/latest/calling_java.html). Then you'd need to instantiate [the constructor](https://github.com/henrypinkard/NDTiffStorage/blob/e8138580b9eebaa22800dcfdb4ec66596ed20023/java/src/main/java/org/micromanager/ndtiffstorage/NDTiffStorage.java#L174) and call some methods from [the API](https://github.com/henrypinkard/NDTiffStorage/blob/main/java/src/main/java/org/micromanager/ndtiffstorage/NDTiffAPI.java), namely `putimage` a bunch of times, `finishedWriting`, and `close`

Happy to answer questions if you take a shot at it

**Comment by henrypinkard** [comment]
Update: there's now an NDTiff writer in python https://github.com/micro-manager/NDTiffStorage/pull/144
