### ISSUE TITLE
Add pytest tests for dataset loading

### ISSUE THREAD

**Issue by ianhi** [micro-manager/NDTiffStorage#29]
### Problem
If people are going to rely on pycromanager to load their datasets then it would be good to have 100% test coverage of the dataset code. Otherwise the potential cost of breakage is high.

### Proposed Solution
add tests for dataset. This basically works by having some simple known test images embedded into the repo. and then you use the dataset loading code to load them and do some `assert`s that everythign is equal.

For example see how aicsimageio does it: https://github.com/AllenCellModeling/aicsimageio/tree/main/aicsimageio/tests/readers

**Comment by henrypinkard** [comment]
Added
